"use client";

import { HandCoins, Receipt } from "@phosphor-icons/react";
import DataTable, { type DataTableColumn } from "@/ui/DataTable";
import { formatarMoeda, formatarDataHora } from "@/lib/formatters";
import type { BatchHistory } from "../export.types";

interface Props {
  batches: BatchHistory[];
  loading?: boolean;
  onLoadMore?: () => void;
  hasMore?: boolean;
  loadingMore?: boolean;
}

export default function HistoryTable({ batches, loading, onLoadMore, hasMore, loadingMore }: Props) {
  const columns: DataTableColumn<BatchHistory>[] = [
    {
      key: "id",
      header: "Batch",
      sortable: true,
      sortAccessor: (l) => l.id,
      render: (l) => <span className="font-semibold text-app-text">#{l.id}</span>,
    },
    {
      key: "type",
      header: "Type",
      sortable: true,
      sortAccessor: (l) => l.batch_type,
      render: (l) => (
        <span className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-small ring-1 bg-[#eef0f3] text-[#5b616e] ring-[#d8dce4]">
          {l.batch_type === "EXPENSE_REPORT" ? <Receipt size={11} /> : <HandCoins size={11} />}
          {l.batch_type === "EXPENSE_REPORT" ? "Expense Report" : "Reimbursement"}
        </span>
      ),
    },
    {
      key: "integration",
      header: "Integration",
      sortable: true,
      sortAccessor: (l) => l.template_used,
      render: (l) => <span className="text-app-text-muted">{l.template_used}</span>,
    },
    {
      key: "items",
      header: "Items",
      sortable: true,
      sortAccessor: (l) => l.item_count,
      render: (l) => (
        <span className="text-app-text-muted tabular-nums">{l.item_count}</span>
      ),
    },
    {
      key: "user",
      header: "Generated by",
      sortable: true,
      sortAccessor: (l) => l.user?.name ?? null,
      render: (l) => <span className="text-app-text-muted">{l.user?.name ?? "—"}</span>,
    },
    {
      key: "date",
      header: "Date",
      sortable: true,
      sortAccessor: (l) => new Date(l.created_at),
      render: (l) => <span className="text-app-text-muted">{formatarDataHora(l.created_at)}</span>,
    },
    {
      key: "amount",
      header: "Amount",
      align: "right",
      sortable: true,
      sortAccessor: (l) => l.total_amount,
      render: (l) => (
        <span className="font-semibold text-app-text tabular-nums">
          {formatarMoeda(l.total_amount)}
        </span>
      ),
    },
  ];

  return (
    <DataTable
      columns={columns}
      rows={batches}
      keyExtractor={(l) => l.id}
      loading={loading}
      tamanho={5}
      defaultSort={{ columnKey: "date", direction: "desc" }}
      onLoadMore={onLoadMore}
      hasMore={hasMore}
      loadingMore={loadingMore}
    />
  );
}
