[PHP]
date.timezone = America/Sao_Paulo

upload_max_filesize = 20M
post_max_size       = 25M

memory_limit = 256M

max_execution_time = 60

display_errors         = Off
display_startup_errors = Off
log_errors             = On

[mbstring]
mbstring.language = pt_BR

[intl]
intl.default_locale = pt_BR
