import { maskCpfCnpj, maskTelefone } from "@/lib/masks";

export type TipoChavePix = "cpf_cnpj" | "telefone" | "email" | "aleatoria";

export const TIPO_CHAVE_PIX_OPTIONS = [
  { value: "cpf_cnpj",  label: "Tax ID" },
  { value: "telefone",  label: "Phone" },
  { value: "email",     label: "Email" },
  { value: "aleatoria", label: "Random key" },
] as const;

export const TIPO_CHAVE_PIX_PLACEHOLDER: Record<TipoChavePix, string> = {
  cpf_cnpj:  "000.000.000-00 or 00.000.000/0000-00",
  telefone:  "(11) 99999-9999",
  email:     "youremail@example.com",
  aleatoria: "Key generated by the bank",
};

const PIX_KEY_TYPES = new Set<string>(["cpf_cnpj", "telefone", "email", "aleatoria"]);

export function isTipoChavePix(val: string): val is TipoChavePix {
  return PIX_KEY_TYPES.has(val);
}

export function inferirTipoChavePix(key: string): TipoChavePix | null {
  if (!key) return null;
  if (key.includes("@")) return "email";
  if (/^\d{3}\.\d{3}\.\d{3}-\d{2}$/.test(key) || /^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/.test(key)) return "cpf_cnpj";
  if (/^\(\d{2}\)\s?\d{4,5}-\d{4}$/.test(key)) return "telefone";
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(key)) return "aleatoria";
  return null;
}

export function aplicarMascaraChavePix(value: string, type: TipoChavePix): string {
  switch (type) {
    case "cpf_cnpj":  return maskCpfCnpj(value);
    case "telefone":  return maskTelefone(value);
    default:          return value.slice(0, 77);
  }
}
